name: Build Book

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pandoc
        uses: pandoc/actions/setup@v1

      - name: Build HTML
        run: |
          pandoc \
            src/index.md \
            src/01-python-intro.md \
            src/02-variables-and-types.md \
            src/03-input-output.md \
            src/04-operators.md \
            src/05-if.md \
            src/06-loop.md \
            src/07-list.md \
            src/08-dict.md \
            src/09-string.md \
            src/10-function.md \
            --metadata-file=meta/metadata.yaml \
            --standalone \
            --toc \
            --css=assets/css/site.css \
            -o docs/index.html

      - name: Build EPUB
        run: |
          mkdir -p output/epub
          pandoc \
            src/index.md \
            src/01-python-intro.md \
            src/02-variables-and-types.md \
            src/03-input-output.md \
            src/04-operators.md \
            src/05-if.md \
            src/06-loop.md \
            src/07-list.md \
            src/08-dict.md \
            src/09-string.md \
            src/10-function.md \
            --metadata-file=meta/metadata.yaml \
            --toc \
            --css=style/ebook.css \
            --epub-cover-image=meta/cover.png \
            -o output/epub/python-for-beginners.epub

      - name: Upload EPUB
        uses: actions/upload-artifact@v4
        with:
          name: python-for-beginners-epub
          path: output/epub/python-for-beginners.epub
